spring:
  datasource:
    url: jdbc:mysql://aliyun.hellozjf.com:3306/test-sso-server?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: Zjf@1234
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    # 不加下面这句则默认为myisam引擎
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
logging:
  level:
    com.hellozjf: debug
  file: ./output/test-sso-server.log
server:
  port: 8081